version: '3.8'

services:
  url_shortener:
    container_name: url_shortener_container
    image: postgres:16.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: url_shortener_pw
      POSTGRES_USER: url_shortener_user
      POSTGRES_DB: url_shortener_db